# Generated by Django 3.2 on 2022-05-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='core',
            name='coins',
        ),
        migrations.AddField(
            model_name='core',
            name='weight',
            field=models.IntegerField(default=50),
        ),
    ]
