# Generated by Django 3.2 on 2022-05-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220526_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='power',
            field=models.IntegerField(default=5),
        ),
    ]
