# Generated by Django 3.2 on 2022-05-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_core_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
