# Generated by Django 3.2 on 2022-06-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_core_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='is_weight_prev_for_next_level',
            field=models.BooleanField(default=False),
        ),
    ]
