# Generated by Django 3.2 on 2022-06-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_core_is_weight_prev_for_next_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='start_weight_for_level',
            field=models.IntegerField(default=50),
        ),
    ]
