# Generated by Django 3.2 on 2022-06-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_core_start_weight_for_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='is_levelup',
            field=models.BooleanField(default=False),
        ),
    ]
