# Generated by Django 3.2 on 2022-06-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='image_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='boost',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
